# Generated by Django 4.2.9 on 2024-04-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='proudct',
            new_name='product',
        ),
    ]
