# Generated by Django 4.2.9 on 2024-04-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_address_x_order_address_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='warehouse',
        ),
    ]
