# Generated by Django 4.2.9 on 2024-04-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userprofile_address_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='environment_tracker',
            field=models.IntegerField(default=0),
        ),
    ]
