# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AUproto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AUproto.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rAUproto.proto\" \n\rUAInitConnect\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\"6\n\x10\x41UConfirmConnect\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\x12\x11\n\tconnected\x18\x02 \x02(\x08\"Y\n\x05Order\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12\x12\n\ntrackingid\x18\x03 \x02(\x03\x12\x12\n\namzaccount\x18\x04 \x02(\x05\x12\x12\n\nupsaccount\x18\x05 \x01(\x05\"L\n\x0c\x41UNeedATruck\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12\x16\n\x06orders\x18\x03 \x03(\x0b\x32\x06.Order\x12\x0e\n\x06seqnum\x18\x04 \x02(\x03\"I\n\x0eUATruckArrived\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x16\n\x06orders\x18\x02 \x03(\x0b\x32\x06.Order\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"G\n\x0c\x41UTruckCanGo\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x16\n\x06orders\x18\x02 \x03(\x0b\x32\x06.Order\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"E\n\x0bUADelivered\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x15\n\x05order\x18\x02 \x02(\x0b\x32\x06.Order\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"8\n\x03\x45rr\x12\x0b\n\x03msg\x18\x01 \x02(\t\x12\x14\n\x0coriginseqnum\x18\x02 \x02(\x03\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"h\n\nAUCommands\x12\x1b\n\x04need\x18\x01 \x03(\x0b\x32\r.AUNeedATruck\x12\x19\n\x02go\x18\x02 \x03(\x0b\x32\r.AUTruckCanGo\x12\x14\n\x06\x65rrors\x18\x03 \x03(\x0b\x32\x04.Err\x12\x0c\n\x04\x61\x63ks\x18\x04 \x03(\x03\"s\n\nUACommands\x12 \n\x07\x61rrived\x18\x01 \x03(\x0b\x32\x0f.UATruckArrived\x12\x1f\n\tdelivered\x18\x02 \x03(\x0b\x32\x0c.UADelivered\x12\x14\n\x06\x65rrors\x18\x03 \x03(\x0b\x32\x04.Err\x12\x0c\n\x04\x61\x63ks\x18\x04 \x03(\x03')
)




_UAINITCONNECT = _descriptor.Descriptor(
  name='UAInitConnect',
  full_name='UAInitConnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='UAInitConnect.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=49,
)


_AUCONFIRMCONNECT = _descriptor.Descriptor(
  name='AUConfirmConnect',
  full_name='AUConfirmConnect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='AUConfirmConnect.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connected', full_name='AUConfirmConnect.connected', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=105,
)


_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Order.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Order.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trackingid', full_name='Order.trackingid', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amzaccount', full_name='Order.amzaccount', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upsaccount', full_name='Order.upsaccount', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=196,
)


_AUNEEDATRUCK = _descriptor.Descriptor(
  name='AUNeedATruck',
  full_name='AUNeedATruck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='AUNeedATruck.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='AUNeedATruck.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orders', full_name='AUNeedATruck.orders', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='AUNeedATruck.seqnum', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=274,
)


_UATRUCKARRIVED = _descriptor.Descriptor(
  name='UATruckArrived',
  full_name='UATruckArrived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UATruckArrived.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orders', full_name='UATruckArrived.orders', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UATruckArrived.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=349,
)


_AUTRUCKCANGO = _descriptor.Descriptor(
  name='AUTruckCanGo',
  full_name='AUTruckCanGo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='AUTruckCanGo.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orders', full_name='AUTruckCanGo.orders', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='AUTruckCanGo.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=422,
)


_UADELIVERED = _descriptor.Descriptor(
  name='UADelivered',
  full_name='UADelivered',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UADelivered.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order', full_name='UADelivered.order', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UADelivered.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=493,
)


_ERR = _descriptor.Descriptor(
  name='Err',
  full_name='Err',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='Err.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='originseqnum', full_name='Err.originseqnum', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='Err.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=551,
)


_AUCOMMANDS = _descriptor.Descriptor(
  name='AUCommands',
  full_name='AUCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='need', full_name='AUCommands.need', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='go', full_name='AUCommands.go', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors', full_name='AUCommands.errors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acks', full_name='AUCommands.acks', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=657,
)


_UACOMMANDS = _descriptor.Descriptor(
  name='UACommands',
  full_name='UACommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arrived', full_name='UACommands.arrived', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delivered', full_name='UACommands.delivered', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors', full_name='UACommands.errors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acks', full_name='UACommands.acks', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=659,
  serialized_end=774,
)

_AUNEEDATRUCK.fields_by_name['orders'].message_type = _ORDER
_UATRUCKARRIVED.fields_by_name['orders'].message_type = _ORDER
_AUTRUCKCANGO.fields_by_name['orders'].message_type = _ORDER
_UADELIVERED.fields_by_name['order'].message_type = _ORDER
_AUCOMMANDS.fields_by_name['need'].message_type = _AUNEEDATRUCK
_AUCOMMANDS.fields_by_name['go'].message_type = _AUTRUCKCANGO
_AUCOMMANDS.fields_by_name['errors'].message_type = _ERR
_UACOMMANDS.fields_by_name['arrived'].message_type = _UATRUCKARRIVED
_UACOMMANDS.fields_by_name['delivered'].message_type = _UADELIVERED
_UACOMMANDS.fields_by_name['errors'].message_type = _ERR
DESCRIPTOR.message_types_by_name['UAInitConnect'] = _UAINITCONNECT
DESCRIPTOR.message_types_by_name['AUConfirmConnect'] = _AUCONFIRMCONNECT
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
DESCRIPTOR.message_types_by_name['AUNeedATruck'] = _AUNEEDATRUCK
DESCRIPTOR.message_types_by_name['UATruckArrived'] = _UATRUCKARRIVED
DESCRIPTOR.message_types_by_name['AUTruckCanGo'] = _AUTRUCKCANGO
DESCRIPTOR.message_types_by_name['UADelivered'] = _UADELIVERED
DESCRIPTOR.message_types_by_name['Err'] = _ERR
DESCRIPTOR.message_types_by_name['AUCommands'] = _AUCOMMANDS
DESCRIPTOR.message_types_by_name['UACommands'] = _UACOMMANDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UAInitConnect = _reflection.GeneratedProtocolMessageType('UAInitConnect', (_message.Message,), dict(
  DESCRIPTOR = _UAINITCONNECT,
  __module__ = 'AUproto_pb2'
  # @@protoc_insertion_point(class_scope:UAInitConnect)
  ))
_sym_db.RegisterMessage(UAInitConnect)

AUConfirmConnect = _reflection.GeneratedProtocolMessageType('AUConfirmConnect', (_message.Message,), dict(
  DESCRIPTOR = _AUCONFIRMCONNECT,
  __module__ = 'AUproto_pb2'
  # @@protoc_insertion_point(class_scope:AUConfirmConnect)
  ))
_sym_db.RegisterMessage(AUConfirmConnect)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), dict(
  DESCRIPTOR = _ORDER,
  __module__ = 'AUproto_pb2'
  # @@protoc_insertion_point(class_scope:Order)
  ))
_sym_db.RegisterMessage(Order)

AUNeedATruck = _reflection.GeneratedProtocolMessageType('AUNeedATruck', (_message.Message,), dict(
  DESCRIPTOR = _AUNEEDATRUCK,
  __module__ = 'AUproto_pb2'
  # @@protoc_insertion_point(class_scope:AUNeedATruck)
  ))
_sym_db.RegisterMessage(AUNeedATruck)

UATruckArrived = _reflection.GeneratedProtocolMessageType('UATruckArrived', (_message.Message,), dict(
  DESCRIPTOR = _UATRUCKARRIVED,
  __module__ = 'AUproto_pb2'
  # @@protoc_insertion_point(class_scope:UATruckArrived)
  ))
_sym_db.RegisterMessage(UATruckArrived)

AUTruckCanGo = _reflection.GeneratedProtocolMessageType('AUTruckCanGo', (_message.Message,), dict(
  DESCRIPTOR = _AUTRUCKCANGO,
  __module__ = 'AUproto_pb2'
  # @@protoc_insertion_point(class_scope:AUTruckCanGo)
  ))
_sym_db.RegisterMessage(AUTruckCanGo)

UADelivered = _reflection.GeneratedProtocolMessageType('UADelivered', (_message.Message,), dict(
  DESCRIPTOR = _UADELIVERED,
  __module__ = 'AUproto_pb2'
  # @@protoc_insertion_point(class_scope:UADelivered)
  ))
_sym_db.RegisterMessage(UADelivered)

Err = _reflection.GeneratedProtocolMessageType('Err', (_message.Message,), dict(
  DESCRIPTOR = _ERR,
  __module__ = 'AUproto_pb2'
  # @@protoc_insertion_point(class_scope:Err)
  ))
_sym_db.RegisterMessage(Err)

AUCommands = _reflection.GeneratedProtocolMessageType('AUCommands', (_message.Message,), dict(
  DESCRIPTOR = _AUCOMMANDS,
  __module__ = 'AUproto_pb2'
  # @@protoc_insertion_point(class_scope:AUCommands)
  ))
_sym_db.RegisterMessage(AUCommands)

UACommands = _reflection.GeneratedProtocolMessageType('UACommands', (_message.Message,), dict(
  DESCRIPTOR = _UACOMMANDS,
  __module__ = 'AUproto_pb2'
  # @@protoc_insertion_point(class_scope:UACommands)
  ))
_sym_db.RegisterMessage(UACommands)


# @@protoc_insertion_point(module_scope)
